---
- hosts: vmlab
  user: student
  become: yes
  vars:
    apache_version: 2.6
    motd_warning: "WARNING: used by ICT faculty/students only.\n"  #installing apache, just updating the previous one
    testserver: yes
    seneca_id: iaoluwajuwon
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Install EPEL repository
      yum:
        name: epel-release    #installing epel rep
        state: present

    - name: Remove 'tree' package
      yum:
        name: tree #using yum to remove tree package
        state: absent

    - name: Set hostname
      hostname:
        name: iaoluwajuwon

    - name: Create new user with sudo access
      user:
        name: iaoluwajuwon
        groups: wheel
        append: yes

    - name: Create SSH directory for the new user
      file:
        path: /home/iaoluwajuwon/.ssh/id_rsa.pub
        state: directory
        mode: 0700
        owner: iaoluwajuwon
        group: iaoluwajuwon

    - name: Copy authorized_keys file
      copy:
        src: /home/instructor/.ssh/id_rsa.pub
        dest: /home/iaoluwajuwon/.ssh/authorized_keys
        owner: iaoluwajuwon
        group: iaoluwajuwon
        mode: 0600

    - name: Set up lab directories
      file:
        path: /home/iaoluwajuwon/ops445i/
        state: directory
        owner: iaoluwajuwon
        group: iaoluwajuwon
        mode: 0755
      with_sequence: start=1 end=9

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
